### ISSUE TITLE
Population of people living in and out of cities in each country

### ISSUE THREAD

**Issue by Jesh-The-Titan** [MartinSVG/SEM-Group-4#30]
As a reporting analyst of the Global Population Census Bureau, I want to have easy access to the population information of people, people living in cities, and people not living in cities in each country, so that I can provide the organisation with population reports.

**Comment by Jesh-The-Titan** [comment]
As a reporting analyst of the Global Population Census Bureau, I want to have easy access to the population information of people, people living in cities, and people not living in cities in each country, so that I can provide the organisation with population reports.

**Comment by AlanGood113** [comment]
Population Report
For the population reports, the following information is requested:

The name of the continent/region/country.
The total population of the continent/region/country.
The total population of the continent/region/country living in cities (including a %).
The total population of the continent/region/country not living in cities (including a %).

The feature must print out in this format.
