### ISSUE TITLE
Population information of different languages

### ISSUE THREAD

**Issue by AlanGood113** [MartinSVG/SEM-Group-4#32]
As a reporting analyst of the Global Population Census Bureau, I want to have easy access to the population information of people speaking Chinese, English, Hindi, Spanish, and Arabic, organised by largest to smallest, so that I can provide the organisation with population reports.

**Comment by EsaiasBurnette** [comment]
@GLMMADHURYU 
This is a great start, but a couple of things need to be changed;
1. The population information is not being pulled from the code
2. The output is empty at this time, only the table is showing

![image.png](https://zube.io/files/martinsvg/dbae786581011b2c88b9749d9fe0c1cb-image.png)

3. The populateLanguageStats needs to be moved to the main App folder

![image.png](https://zube.io/files/martinsvg/689488a5fbd954baa3c8d6ce3a95a47c-image.png)

4. Similarly the printLanguageStats should be moved to the main App folder

![image.png](https://zube.io/files/martinsvg/b087b59d3d454f65a9ac61b88729c8f1-image.png)

5. The PopulateLanguageStats should be moved from this report class and separated to a new class like we have done already, should be named Language

![image.png](https://zube.io/files/martinsvg/0ef2c48e38562aa3cf43060b7f95ae91-image.png)

![image.png](https://zube.io/files/martinsvg/4a3ed27b9b880523f6885f85c32589cc-image.png)

**Comment by GLMMADHURYU** [comment]
Completed working on this, But the workflow failed due to build issues.

**Comment by EsaiasBurnette** [comment]
@GLMMADHURYU 
Good work on this issue overall.

The only issue is that the output is not consistent with the requirement.

The results should only have the 5 languages and the total population with the percentage of the world.

But this looks like it's outputting languages per country and percentage of the country's population.

The percentage of the world population should add up to 100%
