### ISSUE TITLE
Cities in the world organised by largest to smallest population

### ISSUE THREAD

**Issue by EsaiasBurnette** [MartinSVG/SEM-Group-4#7]
As a reporting analyst of the Global Population Census Bureau, I want to have easy access to the population information of cities in the world organised by largest to smallest, so that I can provide the organisation with population reports.

**Comment by eskndhlau** [comment]
Largest to smallest Cities in the World #7

**Comment by eskndhlau** [comment]
As an organization we want to produce a report on any number of top populated cities in the world so that we can have easy access to population information
